11 
    de.renew.gui.CPNDrawing 410 
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13513 "FillColor" "Color" 192 192 192 255 38 65 1058 634 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 3 "LineStyle" "String" "7 3 1 3" "FigureWithID" "Int" 13514 "FillColor" "Color" 255 255 255 255 915 73 177 618 60 68  
        CH.ifa.draw.figures.LineFigure "attributes" "attributes" 2 "LineStyle" "String" "10" "FigureWithID" "Int" 13515 2 468 68 466 702 NULL NULL "CH.ifa.draw.figures.ArrowTip"  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13516 "FillColor" "Color" 192 192 192 255 596 1244 982 394 60 68  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 3 "LineStyle" "String" "7 3 1 3" "FigureWithID" "Int" 13517 "FillColor" "Color" 255 255 255 255 603 1287 367 343 60 68  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 3 "LineStyle" "String" "7 3 1 3" "FigureWithID" "Int" 13518 "FillColor" "Color" 255 255 255 255 765 1287 367 343 60 68  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 3 "LineStyle" "String" "7 3 1 3" "FigureWithID" "Int" 13519 "FillColor" "Color" 255 255 255 255 944 1287 367 343 60 68  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 3 "LineStyle" "String" "7 3 1 3" "FigureWithID" "Int" 13520 "FillColor" "Color" 255 255 255 255 421 348 92 346 60 68  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13521 "FillColor" "Color" 192 192 192 255 1245 581 735 400 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13522 "FillColor" "Color" 255 255 255 255 1267 842 133 124 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13523 "FillColor" "Color" 255 255 255 255 1452 842 133 124 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13524 "FillColor" "Color" 255 255 255 255 1637 842 133 124 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13525 "FillColor" "Color" 255 255 255 255 1822 842 133 124 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13526 "FillColor" "Color" 255 255 255 255 1264 608 689 220 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13527 "FillColor" "Color" 192 192 192 255 1380 282 726 243 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13528 "FillColor" "Color" 192 192 192 255 1650 1413 738 354 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13529 "FillColor" "Color" 192 192 192 255 1827 1084 533 204 8 8  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13530 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1709 1469 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13531 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1695 1453 ":sys(Cmm)" "SansSerif" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator 4 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13532 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 256 461 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13533 2 260 478 187 541 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 22  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13534 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 167 541 24 16 NULL    REF 27 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13535 3 191 545 365 497 458 422 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 27  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13536 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 447 403 41 20 NULL    REF 32 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13537 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 434 388 "Resource a" "SansSerif" 1 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 0 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13538 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 338 541 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13539 3 362 551 414 560 462 641 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 36  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13540 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 447 640 41 20 NULL    REF 41 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13541 2 273 478 341 541 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 22  
            CH.ifa.draw.standard.ChopBoxConnector REF 36   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13542 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 357 148 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13543 2 266 324 266 385 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13560 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 256 304 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13544 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 254 385 24 16 NULL    REF 52 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13545 2 266 401 266 462 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 52  
            CH.ifa.draw.figures.ChopEllipseConnector REF 22   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13546 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 658 461 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13547 2 661 477 583 541 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 57  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13548 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 562 541 24 16 NULL    REF 62 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13549 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 756 541 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13550 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 623 492 "true" "SansSerif" 0 12 0 REF 58 
            CH.ifa.draw.standard.OffsetLocator 12 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13551 2 676 477 757 541 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 57  
            CH.ifa.draw.standard.ChopBoxConnector REF 63   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13552 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 697 492 "false" "SansSerif" 0 12 0 REF 67 
            CH.ifa.draw.standard.OffsetLocator -6 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13553 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 557 148 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13554 2 668 324 668 385 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13563 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 658 304 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13555 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 656 385 24 16 NULL    REF 80 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13556 2 668 401 668 462 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 80  
            CH.ifa.draw.figures.ChopEllipseConnector REF 57   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13557 2 374 166 460 265 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 46  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13558 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 455 265 24 16 NULL    REF 89 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13559 2 455 275 276 313 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 89  
            CH.ifa.draw.figures.ChopEllipseConnector REF 50   REF 50 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13561 2 561 166 473 265 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 74  
            CH.ifa.draw.standard.ChopBoxConnector REF 89   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13562 2 479 275 659 313 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 89  
            CH.ifa.draw.figures.ChopEllipseConnector REF 78   REF 78 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13564 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 271 423 "b" "SansSerif" 0 12 0 REF 53 
            CH.ifa.draw.standard.OffsetLocator 9 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13565 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 676 426 "b" "SansSerif" 0 12 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator 12 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13566 2 187 557 260 622 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 27  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13567 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 256 618 20 20 NULL    REF 112 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13568 2 341 557 273 622 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 36  
            CH.ifa.draw.figures.ChopEllipseConnector REF 112   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13569 3 257 628 66 628 66 421 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 112  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13570 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 54 405 24 16 NULL    REF 121 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13571 3 66 405 66 158 358 158 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 121  
            CH.ifa.draw.figures.ChopEllipseConnector REF 46   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13572 2 583 557 661 623 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 62  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13573 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 658 618 20 20 NULL    REF 130 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13574 2 757 557 676 623 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 63  
            CH.ifa.draw.figures.ChopEllipseConnector REF 130   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13575 3 678 628 868 628 868 421 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 130  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13576 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 857 405 24 16 NULL    REF 139 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13577 3 868 405 868 160 577 158 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 139  
            CH.ifa.draw.figures.ChopEllipseConnector REF 74   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13578 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 218 492 "true" "SansSerif" 0 12 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator 6 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13579 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 286 492 "false" "SansSerif" 0 12 0 REF 42 
            CH.ifa.draw.standard.OffsetLocator -8 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13580 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 586 458 "decision 2" "SansSerif" 1 12 0 REF 57 
            CH.ifa.draw.standard.OffsetLocator -50 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13581 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 192 449 "decision 1" "SansSerif" 1 12 0 REF 22 
            CH.ifa.draw.standard.OffsetLocator -42 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13582 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 602 380 "Agent 2 \ndecides " "SansSerif" 1 12 0 REF 80 
            CH.ifa.draw.standard.OffsetLocator -40 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13583 2 567 541 474 422 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 62  
            CH.ifa.draw.figures.ChopEllipseConnector REF 32   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13584 5 756 550 697 560 577 614 498 616 475 642 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 63  
            CH.ifa.draw.figures.ChopEllipseConnector REF 41   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 13585 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 690 332 "p=c*p1+(1-c)*p2;\nb=Math.random()<p;\nthis:orgP(ag,p1);\nthis:agP(ag,p2);\nthis:sys(c);\nag=2;" "SansSerif" 0 12 0 REF 80 
            CH.ifa.draw.standard.OffsetLocator 84 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13586 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 193 376 "Agent 1 \ndecides " "SansSerif" 1 12 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator -47 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 13587 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 288 332 "p=c*p1+(1-c)*p2;\nb=Math.random()<p;\nthis:orgP(ag,p1);\nthis:agP(ag,p2);\nthis:sys(c);\nag=1;" "SansSerif" 0 12 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator 84 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13588 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 433 658 "Resource b" "SansSerif" 1 12 0 REF 41 
            CH.ifa.draw.standard.OffsetLocator 0 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13589 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 192 192 192 255 149 559 "produce a" "SansSerif" 1 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 0 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13590 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 192 192 192 255 319 559 "produce b" "SansSerif" 1 12 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator 0 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13591 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 192 192 192 255 737 557 "produce b" "SansSerif" 1 12 0 REF 63 
            CH.ifa.draw.standard.OffsetLocator 0 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13592 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 192 192 192 255 543 560 "produce a" "SansSerif" 1 12 0 REF 62 
            CH.ifa.draw.standard.OffsetLocator -1 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13593 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1599 637 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13594 2 1600 650 1436 694 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 191  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13595 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1412 690 24 16 NULL    REF 196 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13596 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1446 690 "split" "SansSerif" 1 12 0 REF 196 
            CH.ifa.draw.standard.OffsetLocator 36 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13597 2 1412 704 1341 745 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 196  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13598 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1322 739 20 20 NULL    REF 204 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13599 2 1436 704 1509 745 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 196  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13610 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1507 739 20 20 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13600 2 1332 759 1331 792 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 204  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13601 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1319 792 24 16 NULL    REF 214 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13602 2 1330 808 1329 869 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 214  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13603 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1319 868 20 20 NULL    REF 219 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13604 2 1329 888 1329 921 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 219  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13605 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1317 921 24 16 NULL    REF 224 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13606 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1356 790 "deleg" "SansSerif" 1 12 0 REF 214 
            CH.ifa.draw.standard.OffsetLocator 42 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13607 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1348 921 "assign" "SansSerif" 1 12 0 REF 224 
            CH.ifa.draw.standard.OffsetLocator 39 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13608 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1289 740 "P[R1]" "SansSerif" 1 12 0 REF 204 
            CH.ifa.draw.standard.OffsetLocator -28 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13609 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1286 869 "P[R1]" "SansSerif" 1 12 0 REF 219 
            CH.ifa.draw.standard.OffsetLocator -28 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 209 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13611 2 1517 759 1517 792 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 209  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13612 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1505 792 24 16 NULL    REF 241 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13613 2 1517 808 1517 869 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 241  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13614 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1507 868 20 20 NULL    REF 246 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13615 2 1517 888 1517 921 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 246  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13616 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1505 921 24 16 NULL    REF 251 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13617 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1542 790 "deleg" "SansSerif" 1 12 0 REF 241 
            CH.ifa.draw.standard.OffsetLocator 42 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13618 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1536 921 "assign" "SansSerif" 1 12 0 REF 251 
            CH.ifa.draw.standard.OffsetLocator 39 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13619 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1474 740 "P[R2]" "SansSerif" 1 12 0 REF 209 
            CH.ifa.draw.standard.OffsetLocator -28 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13620 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1474 869 "P[R2]" "SansSerif" 1 12 0 REF 246 
            CH.ifa.draw.standard.OffsetLocator -28 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13621 2 1619 650 1782 694 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 191  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13622 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1782 690 24 16 NULL    REF 268 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13623 2 1782 704 1711 745 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 268  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13624 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1692 739 20 20 NULL    REF 273 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13625 2 1806 704 1879 745 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 268  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13636 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1877 739 20 20 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13626 2 1702 759 1702 792 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 273  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13627 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1690 792 24 16 NULL    REF 283 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13628 2 1702 808 1702 869 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 283  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13629 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1692 868 20 20 NULL    REF 288 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13630 2 1702 888 1702 921 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 288  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13631 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1690 921 24 16 NULL    REF 293 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13632 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1727 790 "deleg" "SansSerif" 1 12 0 REF 283 
            CH.ifa.draw.standard.OffsetLocator 42 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13633 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1721 921 "assign" "SansSerif" 1 12 0 REF 293 
            CH.ifa.draw.standard.OffsetLocator 39 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13634 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1659 740 "P[R1]" "SansSerif" 1 12 0 REF 273 
            CH.ifa.draw.standard.OffsetLocator -28 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13635 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1659 869 "P[R1]" "SansSerif" 1 12 0 REF 288 
            CH.ifa.draw.standard.OffsetLocator -28 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 278 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13637 2 1887 759 1886 792 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 278  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13638 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1874 792 24 16 NULL    REF 310 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13639 2 1885 808 1884 869 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 310  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13640 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1874 868 20 20 NULL    REF 315 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13641 2 1884 888 1884 921 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 315  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13642 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1872 921 24 16 NULL    REF 320 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13643 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1911 790 "deleg" "SansSerif" 1 12 0 REF 310 
            CH.ifa.draw.standard.OffsetLocator 42 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13644 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1903 921 "assign" "SansSerif" 1 12 0 REF 320 
            CH.ifa.draw.standard.OffsetLocator 39 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13645 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1844 740 "P[R2]" "SansSerif" 1 12 0 REF 278 
            CH.ifa.draw.standard.OffsetLocator -28 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13646 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1841 869 "P[R2]" "SansSerif" 1 12 0 REF 315 
            CH.ifa.draw.standard.OffsetLocator -28 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13647 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1834 662 "this:setP(1,p);\nthis:setP(2,p);\nthis:getState(2);\nthis:getConstr(2,p);" "SansSerif" 0 12 0 REF 268 
            CH.ifa.draw.standard.OffsetLocator 95 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13648 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1301 656 "this:setP(1,p);\nthis:setP(2,p);\nthis:getState(1);\nthis:getConstr(1,p);" "SansSerif" 0 12 0 REF 196 
            CH.ifa.draw.standard.OffsetLocator -68 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13649 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1746 690 "split" "SansSerif" 1 12 0 REF 268 
            CH.ifa.draw.standard.OffsetLocator -34 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13650 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1292 611 "O0" "SansSerif" 0 33 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator -293 -88 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13651 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1274 928 "O1" "SansSerif" 0 33 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator -36 43 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13652 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1459 928 "O2" "SansSerif" 0 33 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator -36 43 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13653 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1644 928 "O1" "SansSerif" 0 33 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator -36 43 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13654 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1829 928 "O2" "SansSerif" 0 33 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator -36 43 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13655 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 974 318 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13656 3 977 318 950 292 981 257 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 357  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13657 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 976 239 20 20 NULL    REF 362 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13658 2 986 259 986 318 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 362  
            CH.ifa.draw.standard.ChopBoxConnector REF 357   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13659 2 986 240 986 162 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 362  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13660 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 974 146 24 16 NULL    REF 371 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13661 3 980 162 951 204 981 242 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 371  
            CH.ifa.draw.figures.ChopEllipseConnector REF 362   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13662 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1006 316 "guard(x>0);\n:step()" "SansSerif" 0 12 0 REF 357 
            CH.ifa.draw.standard.OffsetLocator 55 5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13663 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 0 255 1599 428 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13664 2 1609 448 1609 495 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 379  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13665 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1597 495 24 16 NULL    REF 384 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13666 2 1609 511 1609 638 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 384  
            CH.ifa.draw.figures.ChopEllipseConnector REF 191   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13667 3 1794 443 1843 464 1894 447 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "LineWidth" "Int" 3 "FigureWithID" "Int" 13669 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1770 431 24 16 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13822 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1886 427 63 25 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13668 3 1900 430 1874 415 1794 435 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 394  
            CH.ifa.draw.standard.ChopBoxConnector REF 392   REF 392 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13670 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 489 262 "start round" "SansSerif" 1 12 0 REF 89 
            CH.ifa.draw.standard.OffsetLocator 57 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13671 2 1621 503 1773 503 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 384  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13672 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1772 493 20 20 NULL    REF 406 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13673 2 1782 494 1782 447 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 406  
            CH.ifa.draw.standard.ChopBoxConnector REF 392   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13674 2 1770 438 1619 438 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 392  
            CH.ifa.draw.figures.ChopEllipseConnector REF 379   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13675 2 1948 439 2031 437 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 394  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13676 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 0 255 2031 429 24 16 NULL    REF 418 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13677 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1986 420 "e" "SansSerif" 0 12 0 REF 415 
            CH.ifa.draw.standard.OffsetLocator 0 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13678 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1543 623 "P[R1,R2]" "SansSerif" 1 12 0 REF 191 
            CH.ifa.draw.standard.OffsetLocator -41 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13679 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 355 102 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13680 2 367 118 367 149 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 425  
            CH.ifa.draw.figures.ChopEllipseConnector REF 46   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13681 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 555 102 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13682 2 567 118 567 149 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 430  
            CH.ifa.draw.figures.ChopEllipseConnector REF 74   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13683 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 385 103 ":startR(1)" "SansSerif" 0 12 0 REF 425 
            CH.ifa.draw.standard.OffsetLocator 45 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13684 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 582 105 ":startR(2)" "SansSerif" 0 12 0 REF 430 
            CH.ifa.draw.standard.OffsetLocator 42 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13685 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1320 936 "this:startR(1)" "SansSerif" 0 12 0 REF 224 
            CH.ifa.draw.standard.OffsetLocator 28 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13686 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1510 936 "this:startR(2)" "SansSerif" 0 12 0 REF 251 
            CH.ifa.draw.standard.OffsetLocator 30 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13687 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1695 936 "this:startR(1)" "SansSerif" 0 12 0 REF 293 
            CH.ifa.draw.standard.OffsetLocator 30 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13688 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1877 936 "this:startR(2)" "SansSerif" 0 12 0 REF 320 
            CH.ifa.draw.standard.OffsetLocator 30 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13689 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 1044 516 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13690 2 1044 524 996 524 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 453  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13691 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 976 514 20 20 NULL    REF 457 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13692 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 974 437 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13693 2 986 453 986 515 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 458  
            CH.ifa.draw.figures.ChopEllipseConnector REF 457   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13694 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1029 495 ":orgP(a,p)" "SansSerif" 0 12 0 REF 453 
            CH.ifa.draw.standard.OffsetLocator 1 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13695 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 956 477 "[a,p]" "SansSerif" 0 12 0 REF 459 
            CH.ifa.draw.standard.OffsetLocator -17 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13696 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1009 526 "[a,p]" "SansSerif" 0 12 0 REF 454 
            CH.ifa.draw.standard.OffsetLocator 2 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13697 2 986 534 986 596 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 457  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13698 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 974 596 24 16 NULL    REF 476 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13699 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 954 415 ":setP(a,p)" "SansSerif" 0 12 0 REF 458 
            CH.ifa.draw.standard.OffsetLocator -5 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13700 2 377 161 455 185 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 46  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13701 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 455 181 24 16 NULL    REF 484 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13702 2 558 161 479 185 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 74  
            CH.ifa.draw.standard.ChopBoxConnector REF 484   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13703 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 958 616 ":getP(a,p)" "SansSerif" 0 12 0 REF 476 
            CH.ifa.draw.standard.OffsetLocator 0 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13704 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 921 505 "org. Prob." "SansSerif" 1 12 0 REF 457 
            CH.ifa.draw.standard.OffsetLocator -36 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13705 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 942 200 "500" "SansSerif" 0 12 0 REF 372 
            CH.ifa.draw.standard.OffsetLocator -12 5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13706 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 995 194 "x" "SansSerif" 0 12 0 REF 367 
            CH.ifa.draw.standard.OffsetLocator 12 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13707 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 993 279 "x" "SansSerif" 0 12 0 REF 363 
            CH.ifa.draw.standard.OffsetLocator 10 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13708 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 934 288 "x-1" "SansSerif" 0 12 0 REF 358 
            CH.ifa.draw.standard.OffsetLocator -20 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13709 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 982 242 "0" "SansSerif" 0 12 0 REF 362 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13710 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1605 431 "[]" "SansSerif" 0 12 0 REF 379 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13711 2 996 249 1032 249 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 362  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13712 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 1032 242 24 16 NULL    REF 516 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13713 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1020 258 ":iszero()" "SansSerif" 0 12 0 REF 516 
            CH.ifa.draw.standard.OffsetLocator -1 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13714 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1010 232 "0" "SansSerif" 0 12 0 REF 513 
            CH.ifa.draw.standard.OffsetLocator 0 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13715 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 1867 1133 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13716 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1851 1115 ":agP(a,p);" "SansSerif" 0 12 0 REF 523 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13717 2 1891 1141 1964 1141 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 523  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13718 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 1963 1131 20 20 NULL    REF 530 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13719 3 1983 1141 2041 1131 2099 1139 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 530  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "LineWidth" "Int" 3 "FigureWithID" "Int" 13720 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 2099 1133 24 16 NULL    REF 535 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13721 3 2099 1143 2039 1157 1983 1143 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 535  
            CH.ifa.draw.figures.ChopEllipseConnector REF 530   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13722 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 192 192 192 255 53 388 "this:adapt(1)" "SansSerif" 0 12 0 REF 121 
            CH.ifa.draw.standard.OffsetLocator 24 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13723 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 192 192 192 255 832 387 "this:adapt(2)" "SansSerif" 0 12 0 REF 139 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 3 "LineStyle" "String" "7 3 1 3" "FigureWithID" "Int" 13724 "FillColor" "Color" 255 255 255 255 1123 1287 450 343 60 68  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 3 "LineStyle" "String" "10" "FigureWithID" "Int" 13725 "FillColor" "Color" 192 192 192 255 1265 1352 288 81 44 36  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13726 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 999 1576 80 30 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13727 "FillColor" "Color" 192 192 192 255 672 1445 45 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "LineWidth" "Int" 2 "FigureWithID" "Int" 13728 2 717 1455 845 1455 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 549  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13729 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 844 1440 80 30 NULL    REF 555 
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "LineWidth" "Int" 1 "FigureWithID" "Int" 13730 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1169 1438 45 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "LineStyle" "String" "15 10" "FigureWithID" "Int" 13731 2 924 1455 1169 1448 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 555  
            CH.ifa.draw.standard.ChopBoxConnector REF 556   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13732 2 1191 1458 1191 1502 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 556  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13733 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1151 1501 80 30 NULL    REF 564 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13734 2 1152 1516 1062 1516 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 564  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13738 "FillColor" "Color" 153 255 255 255 1017 1506 45 20 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13735 2 1152 1516 1062 1516 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 564  
            CH.ifa.draw.standard.ChopBoxConnector REF 570   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13736 2 1152 1516 1062 1516 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 564  
            CH.ifa.draw.standard.ChopBoxConnector REF 570   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "LineWidth" "Int" 1 "FigureWithID" "Int" 13737 2 1152 1516 1062 1516 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 564  
            CH.ifa.draw.standard.ChopBoxConnector REF 570   REF 570 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "LineStyle" "String" "15 10" "FigureWithID" "Int" 13739 2 912 1466 1017 1507 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 555  
            CH.ifa.draw.standard.ChopBoxConnector REF 570   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "LineStyle" "String" "15 10" "FigureWithID" "Int" 13740 2 912 1466 1017 1507 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 555  
            CH.ifa.draw.standard.ChopBoxConnector REF 570   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "LineStyle" "String" "15 10" "FigureWithID" "Int" 13741 2 912 1466 1017 1507 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 555  
            CH.ifa.draw.standard.ChopBoxConnector REF 570   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "LineStyle" "String" "15 10" "FigureWithID" "Int" 13742 2 912 1466 1017 1507 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 555  
            CH.ifa.draw.standard.ChopBoxConnector REF 570   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "LineWidth" "Int" 2 "FigureWithID" "Int" 13743 2 1231 1516 1305 1516 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 564  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13744 "FillColor" "Color" 112 219 147 255 1305 1506 45 20 NULL    REF 601 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "LineWidth" "Int" 2 "FigureWithID" "Int" 13745 2 1191 1531 1191 1581 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 564  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "LineWidth" "Int" 3 "FigureWithID" "Int" 13746 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 153 255 255 255 1169 1581 45 20 NULL    REF 606 
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13747 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 844 1345 80 30 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "LineStyle" "String" "10" "FigureWithID" "Int" 13748 2 916 1369 1169 1441 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 607  
            CH.ifa.draw.standard.ChopBoxConnector REF 556   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "LineWidth" "Int" 2 "FigureWithID" "Int" 13749 2 845 1360 717 1360 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 607  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13750 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 672 1350 45 20 NULL    REF 616 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13751 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 657 1468 ":transform()" "SansSerif" 0 12 0 REF 549 
            CH.ifa.draw.standard.OffsetLocator -3 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13752 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 608 1408 "modify team operators \n(deleg, split, refine, exec)" "SansSerif" 1 14 0 REF 549 
            CH.ifa.draw.standard.OffsetLocator 3 -30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13753 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 657 1373 ":transform()" "SansSerif" 0 12 0 REF 616 
            CH.ifa.draw.standard.OffsetLocator -3 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13754 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 653 1314 "modify wfn\n(adapt-Or)" "SansSerif" 1 14 0 REF 616 
            CH.ifa.draw.standard.OffsetLocator 0 -29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "LineWidth" "Int" 2 "FigureWithID" "Int" 13755 2 1351 1400 1414 1400 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13775 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 1307 1390 45 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "LineWidth" "Int" 3 "FigureWithID" "Int" 13756 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 1414 1390 45 20 NULL    REF 635 
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13757 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 0 255 1169 1364 45 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13758 2 1191 1365 1191 1322 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 636  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13798 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 0 255 1169 1302 45 20 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13759 2 1191 1384 1191 1438 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 636  
            CH.ifa.draw.standard.ChopBoxConnector REF 556   
        CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13760 "FillColor" "Color" 0 0 0 255 880 1356 11 12  
        CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13761 "FillColor" "Color" 0 0 0 255 1034 1585 11 12  
        CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13762 "FillColor" "Color" 0 0 0 255 878 1448 11 12  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "LineStyle" "String" "15 10" "FigureWithID" "Int" 13763 2 1039 1577 1039 1526 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 548  
            CH.ifa.draw.standard.ChopBoxConnector REF 570   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "LineStyle" "String" "15 10" "FigureWithID" "Int" 13764 2 1039 1577 1039 1526 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 548  
            CH.ifa.draw.standard.ChopBoxConnector REF 570   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "LineStyle" "String" "15 10" "FigureWithID" "Int" 13765 2 1039 1577 1039 1526 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 548  
            CH.ifa.draw.standard.ChopBoxConnector REF 570   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "LineStyle" "String" "" "LineWidth" "Int" 2 "FigureWithID" "Int" 13766 2 1039 1577 1039 1526 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 548  
            CH.ifa.draw.standard.ChopBoxConnector REF 570   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "LineWidth" "Int" 2 "FigureWithID" "Int" 13767 2 1079 1591 1169 1591 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 548  
            CH.ifa.draw.standard.ChopBoxConnector REF 606   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13768 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 0 255 1414 1506 45 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "LineWidth" "Int" 2 "FigureWithID" "Int" 13769 2 1415 1516 1350 1516 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 666  
            CH.ifa.draw.standard.ChopBoxConnector REF 601   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "LineStyle" "String" "" "LineWidth" "Int" 2 "FigureWithID" "Int" 13770 3 1308 1400 1039 1400 1039 1506 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 633  
            CH.ifa.draw.standard.ChopBoxConnector REF 570   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13771 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1254 1529 "execute wfn activity" "SansSerif" 1 14 0 REF 601 
            CH.ifa.draw.standard.OffsetLocator -1 21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13772 "FillColor" "Color" 0 0 0 255 1430 1510 11 12  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13773 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1432 1509 "[]" "SansSerif" 0 12 0 REF 666 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13774 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1035 1584 "[]" "SansSerif" 0 12 0 REF 548 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 633 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "LineWidth" "Int" 2 "FigureWithID" "Int" 13776 2 1436 1507 1436 1410 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 666  
            CH.ifa.draw.standard.ChopBoxConnector REF 635   
        CH.ifa.draw.figures.EllipseFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13777 "FillColor" "Color" 0 0 0 255 1325 1395 11 12  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13778 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1216 1471 "ongoing\nteam-wfn" "SansSerif" 1 14 0 REF 564 
            CH.ifa.draw.standard.OffsetLocator 61 -28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13779 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1464 1382 "adapt to \nchange of α" "SansSerif" 1 14 0 REF 635 
            CH.ifa.draw.standard.OffsetLocator 70 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13780 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1220 1438 "trigger teamwork" "SansSerif" 1 14 0 REF 556 
            CH.ifa.draw.standard.OffsetLocator 92 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 13781 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 677 1250 "SONAR-Org-Repository" "SansSerif" 1 24 0 NULL NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13782 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1454 1490 "α-knowledge" "SansSerif" 1 14 0 REF 666 
            CH.ifa.draw.standard.OffsetLocator 66 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13783 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 957 1607 "SONAR configuration μ" "SansSerif" 1 14 0 REF 548 
            CH.ifa.draw.standard.OffsetLocator 2 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13784 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1286 1546 "this:transform()" "SansSerif" 0 12 0 REF 601 
            CH.ifa.draw.standard.OffsetLocator 3 37 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "LineStyle" "String" "1 2" "TextAlignment" "Int" 1 "FigureWithID" "Int" 13785 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 948 1518 "delegate" "SansSerif" 1 14 0 REF 570 
            CH.ifa.draw.standard.OffsetLocator -61 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13786 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 967 1534 "refine" "SansSerif" 1 14 0 REF 570 
            CH.ifa.draw.standard.OffsetLocator -51 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13787 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 976 1502 "split" "SansSerif" 1 14 0 REF 570 
            CH.ifa.draw.standard.OffsetLocator -47 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13788 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 926 1550 "assign exec" "SansSerif" 1 14 0 REF 570 
            CH.ifa.draw.standard.OffsetLocator -72 42 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 13789 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1222 1578 "adapt configuration \n(evaluate finished teamwork)" "SansSerif" 1 14 0 REF 606 
            CH.ifa.draw.standard.OffsetLocator 136 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13790 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 538 483 "s" "SansSerif" 0 12 0 REF 159 
            CH.ifa.draw.standard.OffsetLocator 21 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13791 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2104 1094 "adapt to \nchange of α" "SansSerif" 1 14 0 REF 535 
            CH.ifa.draw.standard.OffsetLocator 35 -30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13792 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1181 1292 "manual" "SansSerif" 0 7 0 REF 641 
            CH.ifa.draw.standard.OffsetLocator 2 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.contrib.PolygonFigure "attributes" "attributes" 4 "LineStyle" "String" "10" "FigureWithID" "Int" 13793 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 153 3 884 1359 1093 699 39 699  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13794 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 822 1305 "role-wfn,\norga protocols" "SansSerif" 1 14 0 REF 607 
            CH.ifa.draw.standard.OffsetLocator -10 -38 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.contrib.PolygonFigure "attributes" "attributes" 4 "LineStyle" "String" "10" "FigureWithID" "Int" 13795 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 153 4 887 1451 1975 980 1244 980 1245 593  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13796 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 806 1403 "SONAR organisation\nnetwork model" "SansSerif" 1 14 0 REF 555 
            CH.ifa.draw.standard.OffsetLocator -5 -35 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13797 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1047 1348 "sensor state (OPA)" "SansSerif" 1 14 0 REF 636 
            CH.ifa.draw.standard.OffsetLocator -77 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 641 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13799 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1078 1306 "sense (OPA)" "SansSerif" 1 14 0 REF 641 
            CH.ifa.draw.standard.OffsetLocator -70 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 13800 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1100 1252 "SONAR-MAPE-Loop" "SansSerif" 1 24 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13801 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1250 546 "SONAR Organisation " "SansSerif" 0 33 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator -193 -216 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        CH.ifa.draw.contrib.PolygonFigure "attributes" "attributes" 4 "LineStyle" "String" "10" "FigureWithID" "Int" 13802 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 153 4 1331 1402 2288 1287 1828 1288 1826 1126  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13803 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1278 1358 "decision logic δ\n (OMA)" "SansSerif" 1 14 0 REF 633 
            CH.ifa.draw.standard.OffsetLocator 6 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13804 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 69 26 "Team Workflow" "SansSerif" 0 33 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -375 -337 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13805 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1473 477 "trigger teamwork" "SansSerif" 1 14 0 REF 384 
            CH.ifa.draw.standard.OffsetLocator -73 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13806 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 2031 1112 "[a,p]" "SansSerif" 0 12 0 REF 531 
            CH.ifa.draw.standard.OffsetLocator 3 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13807 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 2028 1157 "[a,q]" "SansSerif" 0 12 0 REF 536 
            CH.ifa.draw.standard.OffsetLocator 0 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13808 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1915 1144 "[a,p]" "SansSerif" 0 12 0 REF 527 
            CH.ifa.draw.standard.OffsetLocator 1 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13809 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 374 490 "s" "SansSerif" 0 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 53 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13810 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 397 540 "s" "SansSerif" 0 12 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator -12 -49 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13811 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 547 616 "s" "SansSerif" 0 12 0 REF 163 
            CH.ifa.draw.standard.OffsetLocator -65 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13812 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 192 192 192 255 437 287 "this:step()" "SansSerif" 0 12 0 REF 89 
            CH.ifa.draw.standard.OffsetLocator -2 21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13813 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1873 406 "e" "SansSerif" 0 12 0 REF 395 
            CH.ifa.draw.standard.OffsetLocator 29 -12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13814 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 192 192 192 255 435 198 ":stopWFN();\nthis:iszero();" "SansSerif" 0 12 0 REF 484 
            CH.ifa.draw.standard.OffsetLocator 3 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13815 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 955 558 "[a,p]" "SansSerif" 0 12 0 REF 472 
            CH.ifa.draw.standard.OffsetLocator -18 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13816 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1709 1623 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13817 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 2269 1449 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13818 2 1941 446 2031 475 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 394  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13819 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 0 255 2031 471 24 16 NULL    REF 795 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13820 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1983 442 "e" "SansSerif" 0 12 0 REF 792 
            CH.ifa.draw.standard.OffsetLocator 0 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13821 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2006 489 ":getTime(e)" "SansSerif" 0 12 0 REF 795 
            CH.ifa.draw.standard.OffsetLocator -4 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 394 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13823 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1865 459 "SONAR \nconfiguration μ" "SansSerif" 1 14 0 REF 394 
            CH.ifa.draw.standard.OffsetLocator 4 37 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13824 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1814 466 "e+1" "SansSerif" 0 12 0 REF 389 
            CH.ifa.draw.standard.OffsetLocator -18 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13825 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 2125 1452 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13826 2 2149 1459 2270 1459 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 808  
            CH.ifa.draw.figures.ChopEllipseConnector REF 791   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13827 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 2161 1443 "[e,p1,p2,p,r1,r2]" "SansSerif" 0 12 0 REF 809 
            CH.ifa.draw.standard.OffsetLocator 2 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13828 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2219 1427 "Zeitreihe (OMA)" "SansSerif" 1 12 0 REF 791 
            CH.ifa.draw.standard.OffsetLocator -12 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13829 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1913 432 "1" "SansSerif" 0 12 0 REF 394 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13830 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1640 392 "adapt configuration \n(evaluate finished teamwork)" "SansSerif" 1 14 0 REF 392 
            CH.ifa.draw.standard.OffsetLocator -37 -30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13831 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1405 243 "OPA Model" "SansSerif" 0 33 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator -251 -141 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13832 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 1862 1671 20 20 NULL REF 530  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13833 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1864 1481 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13834 2 1873 1562 1872 1672 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 13847 1862 1546 24 16 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 828   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13835 2 1862 1551 1731 1530 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 833  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13836 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1711 1518 20 20 NULL    REF 839 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13837 2 1721 1519 1721 1485 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 839  
            CH.ifa.draw.standard.ChopBoxConnector REF 18   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13838 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1781 1533 "Cmm" "SansSerif" 0 12 0 REF 835 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13839 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1706 1495 "Cmm" "SansSerif" 0 12 0 REF 840 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13840 2 1862 1555 1731 1578 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 833  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13841 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1711 1569 20 20 NULL    REF 853 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13842 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1778 1559 "Ctrans" "SansSerif" 0 12 0 REF 849 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13843 2 1721 1589 1721 1623 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 853  
            CH.ifa.draw.standard.ChopBoxConnector REF 790   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13844 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1703 1599 "Ctrans" "SansSerif" 0 12 0 REF 857 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13845 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1942 1117 "OMA prob" "SansSerif" 1 12 0 REF 530 
            CH.ifa.draw.standard.OffsetLocator 0 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13846 2 1874 1501 1874 1546 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 829  
            CH.ifa.draw.standard.ChopBoxConnector REF 833   REF 833 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13848 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 192 192 192 255 135 575 "this:getTime(s);\nthis:incResA();" "SansSerif" 0 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 0 41 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13849 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 192 192 192 255 530 575 "this:getTime(s);\nthis:incResA();" "SansSerif" 0 12 0 REF 62 
            CH.ifa.draw.standard.OffsetLocator 0 41 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13850 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 2143 1629 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13851 3 2149 1645 2134 1669 2151 1684 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 876  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13852 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 2147 1680 20 20 NULL    REF 881 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13853 3 2162 1683 2172 1666 2159 1645 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 881  
            CH.ifa.draw.standard.ChopBoxConnector REF 876   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13854 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 2116 1659 "x+1" "SansSerif" 0 12 0 REF 877 
            CH.ifa.draw.standard.OffsetLocator -14 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13855 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 2179 1661 "x" "SansSerif" 0 12 0 REF 882 
            CH.ifa.draw.standard.OffsetLocator 17 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13856 2 2166 1694 2227 1725 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 881  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13857 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 2227 1723 24 16 NULL    REF 896 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13858 3 2227 1731 2157 1731 2157 1700 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 896  
            CH.ifa.draw.figures.ChopEllipseConnector REF 881   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13859 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1692 288 "this:stopWFN();\nthis:getP(1,p1);\nthis:getP(2,p2);\nthis:agP(1,q1);\nthis:agP(2,q2);\nthis:resetRes(r1,r2);\nthis:log(e,q1,q2,p1,r1,r2)" "SansSerif" 0 12 0 REF 392 
            CH.ifa.draw.standard.OffsetLocator -15 -99 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13860 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 2306 1629 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13861 3 2309 1645 2297 1658 2315 1683 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 904  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13862 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 2310 1680 20 20 NULL    REF 909 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13863 3 2326 1683 2336 1667 2322 1645 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 909  
            CH.ifa.draw.standard.ChopBoxConnector REF 904   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13864 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 2343 1661 "x" "SansSerif" 0 12 0 REF 910 
            CH.ifa.draw.standard.OffsetLocator 17 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13865 2 2312 1695 2251 1724 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 909  
            CH.ifa.draw.standard.ChopBoxConnector REF 896   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13866 3 2251 1730 2320 1730 2320 1700 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 896  
            CH.ifa.draw.figures.ChopEllipseConnector REF 909   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13867 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 192 192 192 255 2293 1612 ":incResB();" "SansSerif" 0 12 0 REF 904 
            CH.ifa.draw.standard.OffsetLocator 5 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13868 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 192 192 192 255 2125 1609 ":incResA();" "SansSerif" 0 12 0 REF 876 
            CH.ifa.draw.standard.OffsetLocator 0 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13869 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2153 1683 "0" "SansSerif" 0 12 0 REF 881 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13870 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2316 1683 "0" "SansSerif" 0 12 0 REF 909 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13871 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 192 192 192 255 308 575 "this:getTime(s);\nthis:incResB();" "SansSerif" 0 12 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator 2 41 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13872 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 192 192 192 255 726 575 "this:getTime(s);\nthis:incResB();" "SansSerif" 0 12 0 REF 63 
            CH.ifa.draw.standard.OffsetLocator 2 41 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13873 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 995 140 "guard(x==0);\n:resetLoopCount()" "SansSerif" 0 12 0 REF 371 
            CH.ifa.draw.standard.OffsetLocator 60 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13874 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1471 497 "this:resetLoopCount();" "SansSerif" 0 12 0 REF 384 
            CH.ifa.draw.standard.OffsetLocator -75 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13875 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1971 409 ":getState(((e+1)%2)+1)" "SansSerif" 0 12 0 REF 418 
            CH.ifa.draw.standard.OffsetLocator -6 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13876 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1481 510 "this:getTime(e); guard(e<9)" "SansSerif" 0 12 0 REF 384 
            CH.ifa.draw.standard.OffsetLocator -48 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13877 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2126 1476 ":log(e,q1,q2,q,res1,res2);\np1= Math.round(100*q1);\np2= Math.round(100*q2);\np =  Math.round(100*q);\nr1= Math.round(res1/10);\nr2= Math.round(res2/10);\n" "SansSerif" 0 10 0 REF 808 
            CH.ifa.draw.standard.OffsetLocator 51 61 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13878 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1846 1637 "[1,p1];[2,p2]" "SansSerif" 0 12 0 REF 830 
            CH.ifa.draw.standard.OffsetLocator 12 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13879 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1882 1677 "OMA prob" "SansSerif" 1 12 0 REF 828 
            CH.ifa.draw.standard.OffsetLocator 41 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13880 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1831 1513 "[Cmm,Ctrans,eta]" "SansSerif" 0 12 0 REF 866 
            CH.ifa.draw.standard.OffsetLocator 7 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13881 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1896 1533 "p1=0.7;\np2=0.4;" "SansSerif" 0 12 0 REF 833 
            CH.ifa.draw.standard.OffsetLocator 47 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13882 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 2330 1716 "0" "SansSerif" 0 12 0 REF 921 
            CH.ifa.draw.standard.OffsetLocator 49 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13883 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 2145 1711 "0" "SansSerif" 0 12 0 REF 897 
            CH.ifa.draw.standard.OffsetLocator -43 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13884 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 2197 1694 "x" "SansSerif" 0 12 0 REF 892 
            CH.ifa.draw.standard.OffsetLocator 4 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13885 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 2267 1699 "y" "SansSerif" 0 12 0 REF 917 
            CH.ifa.draw.standard.OffsetLocator -11 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13886 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 2278 1659 "x+1" "SansSerif" 0 12 0 REF 905 
            CH.ifa.draw.standard.OffsetLocator -16 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13887 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2216 1738 ":resetRes(x,y)" "SansSerif" 0 12 0 REF 896 
            CH.ifa.draw.standard.OffsetLocator 16 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13888 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1690 1641 ":getC(Ctrans)" "SansSerif" 0 12 0 REF 790 
            CH.ifa.draw.standard.OffsetLocator 6 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13889 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1681 1440 "mix Org & Ag" "SansSerif" 1 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator 2 -30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "LineWidth" "Int" 1 "FigureWithID" "Int" 13891 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 2161 1205 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13892 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2153 1203 ":gradient(p,g);\nthis:getState(2);\nthis:getETA(eta);\ny=p-0.5;\ndelta = 0.3;\ng= eta*4*y*(y*y - delta*delta);\n\n" "SansSerif" 0 11 0 REF 994 
            CH.ifa.draw.standard.OffsetLocator 60 46 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13893 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2168 1204 "g" "SansSerif" 1 14 0 REF 994 
            CH.ifa.draw.standard.OffsetLocator -1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "LineWidth" "Int" 1 "FigureWithID" "Int" 13894 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 1970 1203 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13895 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1961 1201 ":gradient(p,g);\nthis:getState(1);\nthis:getETA(eta);\ny=p-0.6;\ndelta = 0.1;\ng = eta*4*y*(y*y - delta*delta);\n\n" "SansSerif" 0 11 0 REF 1001 
            CH.ifa.draw.standard.OffsetLocator 60 46 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13896 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1977 1202 "g" "SansSerif" 1 14 0 REF 1001 
            CH.ifa.draw.standard.OffsetLocator -1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 13897 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2125 1557 "action System.out.println(e\n+\", \"+p1+\", \"+p2 \n+ \", \"+ p\n+ \", \"+r1+\", \"+r2)" "SansSerif" 0 9 0 REF 808 
            CH.ifa.draw.standard.OffsetLocator 49 119 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13898 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1962 1744 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13899 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1913 1731 ":getConstr(1,0.6);" "SansSerif" 0 12 0 REF 1011 
            CH.ifa.draw.standard.OffsetLocator -10 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13900 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 2088 1745 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13901 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2039 1732 ":getConstr(2,0.0);" "SansSerif" 0 12 0 REF 1015 
            CH.ifa.draw.standard.OffsetLocator -10 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13902 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1796 1681 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 13903 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1798 1593 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13904 2 1808 1613 1808 1681 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1020  
            CH.ifa.draw.standard.ChopBoxConnector REF 1019   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13905 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1799 1640 "eta" "SansSerif" 0 12 0 REF 1021 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13906 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1779 1699 ":getETA(eta)" "SansSerif" 0 12 0 REF 1019 
            CH.ifa.draw.standard.OffsetLocator 6 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13907 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1795 1715 "learning rate" "SansSerif" 1 12 0 REF 1019 
            CH.ifa.draw.standard.OffsetLocator 26 33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13908 2 1863 1562 1816 1598 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 833  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1020   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13909 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1830 1573 "eta" "SansSerif" 0 12 0 REF 1033 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13910 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1671 1653 "agent adapts \nto org " "SansSerif" 1 12 0 REF 790 
            CH.ifa.draw.standard.OffsetLocator -8 37 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13911 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1975 1047 "OMA Model" "SansSerif" 0 33 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator -26 -120 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 13912 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1897 1559 "action System.out.println(\n\"Cmm = \" +Cmm \n+\" \" + \"C_transparancy = \" + Ctrans\n+\" \" + \"OMA-eta = \" + eta\n+\" \"+ \"p1 = \" + p1\n+\" \" + \"p2 = \" + p2 \n+ \"\\n\" + \" ; p1; p2; p_Org; res A; res B\")" "SansSerif" 0 9 0 REF 833 
            CH.ifa.draw.standard.OffsetLocator 112 43 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13913 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1863 1547 "init" "SansSerif" 1 12 0 REF 833 
            CH.ifa.draw.standard.OffsetLocator -1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13914 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2180 1085 ":adapt(a);\nthis:gradient(p,g);\nthis:orgP(a,p1);\nthis:getC(c);\nq=(1-c)*(p-g) + c*p1;" "SansSerif" 0 12 0 REF 535 
            CH.ifa.draw.standard.OffsetLocator 135 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 13915 1863 1437 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13916 2 1874 1453 1874 1482 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1055  
            CH.ifa.draw.figures.ChopEllipseConnector REF 829   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13917 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1898 1438 ":new(x)" "SansSerif" 0 12 0 REF 1055 
            CH.ifa.draw.standard.OffsetLocator 44 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13918 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1889 1464 "meta parameter" "SansSerif" 1 12 0 REF 829 
            CH.ifa.draw.standard.OffsetLocator 64 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13919 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1871 1460 "x" "SansSerif" 0 12 0 REF 1056 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 13920 2 1600 438 1521 438 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 379  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 2 "FigureWithID" "Int" 13921 "FillColor" "Color" 255 199 158 255 1497 430 24 16 NULL    REF 1073 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13922 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1457 379 ":stop(); \nthis:getTime(e);\nguard(e>=9)" "SansSerif" 0 12 0 REF 1073 
            CH.ifa.draw.standard.OffsetLocator -7 -37 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13890 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1664 1370 "Meta Parameters/Initialisiation/Logging" "SansSerif" 0 33 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator -37 -201 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5    NULL  